### ISSUE TITLE
Is w3.org blocked in China?

### ISSUE THREAD

**Issue by wi24rd** [w3c/chinese-ig#245]
When I access http://w3.org/ or http://www.w3.org/ 
it will be redirected to http://39.102.194.95/ which says "您访问的网站/网页存在诈骗风险，请注意个人信息和财产安全"(the website you access has the risk of fraud)  and is authorized by National Anti-fraud Center, MIIT and China Unicom.
When I access https://www.w3.org the response can't be gotten with error ERR_CONNECTION_RESET

![image](https://user-images.githubusercontent.com/14029004/174424123-64f2d5f2-e08c-42a6-ae36-f50cbce0af1e.png)
While https://lists.w3.org/ is accessible.

**Comment by xfq** [comment]
Thanks for your report. We're aware of this issue and are working to resolve it.
