### ISSUE TITLE
【Task Force】召集小程序标准化的讨论

### ISSUE THREAD

**Issue by tayqassqan** [w3c/chinese-ig#62]
计划于19年4月或者5月召集小程序相关标准的讨论，议题包括：

- 小程序厂商技术方案分享以及对于标准化的建议
- 业界小程序框架技术分享和标准化建议
- 开发者代表对于小程序的标准化建议

**Comment by tayqassqan** [comment]
小程序厂商可以重点讨论的标准化方向有：

- AI相关API
- XR相关API
- 区块链相关API

也欢迎大家补充！

**Comment by ysbcc** [comment]
小程序出现的原因是H5体验不行，要对症下药，提升H5的性能和体验，对标原生开发，才是正道。

**Comment by baoyouwangning** [comment]
> 小程序厂商可以重点讨论的标准化方向有：
> 
> * AI相关API
> * XR相关API
> * 区块链相关API
> 
> 也欢迎大家补充！

视频相关API

**Comment by tayqassqan** [comment]
> 视频相关API
请问有更详细的建议吗？
也欢迎到[下一代移动 Web 应用标准化研讨会](https://github.com/w3c/chinese-ig/blob/master/meetings/2019-05-11.md)参与讨论和发表看法，建议：）

**Comment by arthas-cui** [comment]
webview相关api吧。 小程序内使用webview， 用js bridge来操作小程序本身， 这个各家支持都不一样。 实际上webview非常重要， 不是简单地“向H5妥协”。

**Comment by calent** [comment]
建议H5可以吸取小程序的一些能力，如：
1. 物与物的IOT相关API（如蓝牙设备等）；
2. 消息通知能力（如打通手机“通知中心”）；
3. 界面交互相关（如下拉刷新、上拉触底）；

**Comment by performonkey** [comment]
> 建议H5可以吸取小程序的一些能力，如：
> 
> 1. 物与物的IOT相关API（如蓝牙设备等）；
> 2. 消息通知能力（如打通手机“通知中心”）；
> 3. 界面交互相关（如下拉刷新、上拉触底）；

[蓝牙](https://webbluetoothcg.github.io/web-bluetooth/) 和 [消息通知](https://www.w3.org/TR/push-api/) 已经有了

下拉/上拉 这些交互逻辑还是应该由程序根据场景实现，不应该用标准完全统一

**Comment by laden666666** [comment]
> 计划于19年4月或者5月召集小程序相关标准的讨论

@tayqassqan 有视频直播吗？或者有视频录像吗？

**Comment by tayqassqan** [comment]
> > 计划于19年4月或者5月召集小程序相关标准的讨论
> 
> @tayqassqan 有视频直播吗？或者有视频录像吗？

会在W3C会员范围公开会议纪要。

**Comment by beatles-chameleon** [comment]
API 接口协议：定义基础接口能力标准。
内置组件协议：定义基础 UI 组件标准。
框架协议：定义生命周期、路由等框架标准。
DSL 协议：定义视图和逻辑层的关联语法标准。
多态实现协议：定义允许用户使用差异化能力标准。

参考：https://cml.js.org/doc/extend/extend.html

**Comment by xfq** [comment]
本次会议已结束，现场纪要及会后总结可见[会议页面](https://github.com/w3c/chinese-ig/blob/master/meetings/2019-05-11.md)。

关于小程序标准化的具体问题，可以在新的issue里讨论。
